module.exports = {
  ApplyBodyWrench: require('./ApplyBodyWrench.js'),
  ApplyJointEffort: require('./ApplyJointEffort.js'),
  BodyRequest: require('./BodyRequest.js'),
  DeleteLight: require('./DeleteLight.js'),
  GetJointProperties: require('./GetJointProperties.js'),
  DeleteModel: require('./DeleteModel.js'),
  GetLightProperties: require('./GetLightProperties.js'),
  GetLinkState: require('./GetLinkState.js'),
  GetLinkProperties: require('./GetLinkProperties.js'),
  GetModelProperties: require('./GetModelProperties.js'),
  GetModelState: require('./GetModelState.js'),
  GetWorldProperties: require('./GetWorldProperties.js'),
  GetPhysicsProperties: require('./GetPhysicsProperties.js'),
  SetJointTrajectory: require('./SetJointTrajectory.js'),
  SetJointProperties: require('./SetJointProperties.js'),
  JointRequest: require('./JointRequest.js'),
  SetLightProperties: require('./SetLightProperties.js'),
  SetLinkState: require('./SetLinkState.js'),
  SetLinkProperties: require('./SetLinkProperties.js'),
  SetModelConfiguration: require('./SetModelConfiguration.js'),
  SetModelState: require('./SetModelState.js'),
  SpawnModel: require('./SpawnModel.js'),
  SetPhysicsProperties: require('./SetPhysicsProperties.js'),
};
