module.exports = {
  AveragingAction: require('./AveragingAction.js'),
  AveragingActionFeedback: require('./AveragingActionFeedback.js'),
  AveragingActionGoal: require('./AveragingActionGoal.js'),
  AveragingFeedback: require('./AveragingFeedback.js'),
  AveragingActionResult: require('./AveragingActionResult.js'),
  AveragingGoal: require('./AveragingGoal.js'),
  AveragingResult: require('./AveragingResult.js'),
  FibonacciAction: require('./FibonacciAction.js'),
  FibonacciActionFeedback: require('./FibonacciActionFeedback.js'),
  FibonacciActionGoal: require('./FibonacciActionGoal.js'),
  FibonacciFeedback: require('./FibonacciFeedback.js'),
  FibonacciActionResult: require('./FibonacciActionResult.js'),
  FibonacciGoal: require('./FibonacciGoal.js'),
  FibonacciResult: require('./FibonacciResult.js'),
};
