#!/bin/bash
. init.sh

# Make sure name is generated by running "node /catkin_ws/src/stagehands-js/packages/bot/dist/getName.js" and saving output to bash variable
export NAME=$(node /catkin_ws/src/stagehands-js/packages/bot/dist/getName.js)

# Set ROS hostname to <name>-stagehands.local
export ROS_HOSTNAME=$NAME-stagehands.local
echo "Launching ROS with hostname $ROS_HOSTNAME"

# # Launch ROS master
# roscore &

# Launch the management node
cd /catkin_ws/src/stagehands-js/packages/bot
ls /catkin_ws/devel/share/gennodejs/ros/stagehands_ros/
# node -e "require(\"rosnodejs\"); console.log(require(\"\/catkin_ws\/devel\/share\/gennodejs\/ros\/stagehands_ros\/_index.js\"))"
# node --

# Start ssh daemon
# service ssh start

# Prevent container from exiting
# tail -f /dev/null