# Make sure name is generated by running "node /catkin_ws/src/stagehands-js/packages/bot/dist/getName.js" and saving output to bash variable
export NAME=$(node /catkin_ws/src/stagehands-js/packages/bot/dist/getName.js)

# Set ROS hostname to <name>-stagehands.local
export ROS_HOSTNAME=$NAME-stagehands.local

export TURTLEBOT3_MODEL=waffle_pi