// Generated by gencpp from file stagehands/setTargetPose.msg
// DO NOT EDIT!


#ifndef STAGEHANDS_MESSAGE_SETTARGETPOSE_H
#define STAGEHANDS_MESSAGE_SETTARGETPOSE_H

#include <ros/service_traits.h>


#include <stagehands/setTargetPoseRequest.h>
#include <stagehands/setTargetPoseResponse.h>


namespace stagehands
{

struct setTargetPose
{

typedef setTargetPoseRequest Request;
typedef setTargetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setTargetPose
} // namespace stagehands


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stagehands::setTargetPose > {
  static const char* value()
  {
    return "b2641e4b932d1b80a79d7568f7c58323";
  }

  static const char* value(const ::stagehands::setTargetPose&) { return value(); }
};

template<>
struct DataType< ::stagehands::setTargetPose > {
  static const char* value()
  {
    return "stagehands/setTargetPose";
  }

  static const char* value(const ::stagehands::setTargetPose&) { return value(); }
};


// service_traits::MD5Sum< ::stagehands::setTargetPoseRequest> should match
// service_traits::MD5Sum< ::stagehands::setTargetPose >
template<>
struct MD5Sum< ::stagehands::setTargetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stagehands::setTargetPose >::value();
  }
  static const char* value(const ::stagehands::setTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stagehands::setTargetPoseRequest> should match
// service_traits::DataType< ::stagehands::setTargetPose >
template<>
struct DataType< ::stagehands::setTargetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::stagehands::setTargetPose >::value();
  }
  static const char* value(const ::stagehands::setTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stagehands::setTargetPoseResponse> should match
// service_traits::MD5Sum< ::stagehands::setTargetPose >
template<>
struct MD5Sum< ::stagehands::setTargetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stagehands::setTargetPose >::value();
  }
  static const char* value(const ::stagehands::setTargetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stagehands::setTargetPoseResponse> should match
// service_traits::DataType< ::stagehands::setTargetPose >
template<>
struct DataType< ::stagehands::setTargetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::stagehands::setTargetPose >::value();
  }
  static const char* value(const ::stagehands::setTargetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STAGEHANDS_MESSAGE_SETTARGETPOSE_H
