// Generated by gencpp from file stagehands_custom_nodes/setTargetPose.msg
// DO NOT EDIT!


#ifndef STAGEHANDS_CUSTOM_NODES_MESSAGE_SETTARGETPOSE_H
#define STAGEHANDS_CUSTOM_NODES_MESSAGE_SETTARGETPOSE_H

#include <ros/service_traits.h>


#include <stagehands_custom_nodes/setTargetPoseRequest.h>
#include <stagehands_custom_nodes/setTargetPoseResponse.h>


namespace stagehands_custom_nodes
{

struct setTargetPose
{

typedef setTargetPoseRequest Request;
typedef setTargetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setTargetPose
} // namespace stagehands_custom_nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stagehands_custom_nodes::setTargetPose > {
  static const char* value()
  {
    return "b2641e4b932d1b80a79d7568f7c58323";
  }

  static const char* value(const ::stagehands_custom_nodes::setTargetPose&) { return value(); }
};

template<>
struct DataType< ::stagehands_custom_nodes::setTargetPose > {
  static const char* value()
  {
    return "stagehands_custom_nodes/setTargetPose";
  }

  static const char* value(const ::stagehands_custom_nodes::setTargetPose&) { return value(); }
};


// service_traits::MD5Sum< ::stagehands_custom_nodes::setTargetPoseRequest> should match
// service_traits::MD5Sum< ::stagehands_custom_nodes::setTargetPose >
template<>
struct MD5Sum< ::stagehands_custom_nodes::setTargetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stagehands_custom_nodes::setTargetPose >::value();
  }
  static const char* value(const ::stagehands_custom_nodes::setTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stagehands_custom_nodes::setTargetPoseRequest> should match
// service_traits::DataType< ::stagehands_custom_nodes::setTargetPose >
template<>
struct DataType< ::stagehands_custom_nodes::setTargetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::stagehands_custom_nodes::setTargetPose >::value();
  }
  static const char* value(const ::stagehands_custom_nodes::setTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stagehands_custom_nodes::setTargetPoseResponse> should match
// service_traits::MD5Sum< ::stagehands_custom_nodes::setTargetPose >
template<>
struct MD5Sum< ::stagehands_custom_nodes::setTargetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stagehands_custom_nodes::setTargetPose >::value();
  }
  static const char* value(const ::stagehands_custom_nodes::setTargetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stagehands_custom_nodes::setTargetPoseResponse> should match
// service_traits::DataType< ::stagehands_custom_nodes::setTargetPose >
template<>
struct DataType< ::stagehands_custom_nodes::setTargetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::stagehands_custom_nodes::setTargetPose >::value();
  }
  static const char* value(const ::stagehands_custom_nodes::setTargetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STAGEHANDS_CUSTOM_NODES_MESSAGE_SETTARGETPOSE_H
