version: "3.8"
services:
  ros-dev:
    build: ./basebot
    container_name: basebot-dev-container
    volumes:
      - ./basebot/.vscode:/catkin_ws/.vscode
      - ./basebot/src:/catkin_ws/src
      - ./basebot/map:/map
      - ./basebot/scripts:/scripts
      - /catkin_ws/devel
      - /catkin_ws/build
      - /catkin_ws/logs
      - /catkin_ws/install
    environment:
      - HOST_OS=macos
    # Keep it open for development
    stdin_open: true
    tty: true
    network_mode: host