version: "3.3"
services:
  ros-dev:
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix:rw'
    devices:
      - /dev/dri
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - HOST_OS=linux