version: "3.8"
services:
  ros-dev:
    build:
      context: ../
      dockerfile: ./ros/basebot/Dockerfile
    container_name: basebot-dev-container
    volumes:
      - ./basebot/.vscode:/catkin_ws/.vscode
      - ./basebot/src:/catkin_ws/src
      - ./basebot/map:/map
      - ./basebot/scripts:/scripts
      - ../packages:/catkin_ws/src/stagehands-js/packages
      - ../package.json:/catkin_ws/src/stagehands-js/package.json
      - ../package-lock.json:/catkin_ws/src/stagehands-js/package-lock.json
      - /catkin_ws/devel
      - /catkin_ws/build
      - /catkin_ws/logs
      - /catkin_ws/install
    environment:
      - HOST_OS=macos
    # Keep it open for development
    stdin_open: true
    tty: true
    network_mode: host