version: "3.8"
services:
  ros-dev:
    build:
      context: ../
      dockerfile: ./ros/basebot/Dockerfile
    container_name: basebot-dev-container
    volumes:
      - ./ros/basebot/.vscode:/catkin_ws/.vscode
      - ./ros/basebot/src:/catkin_ws/src
      - ./ros/basebot/map:/map
      - ./ros/basebot/scripts:/scripts
      - /catkin_ws/devel
      - /catkin_ws/build
      - /catkin_ws/logs
      - /catkin_ws/install
    environment:
      - HOST_OS=win_wsl
    # Keep it open for development
    stdin_open: true
    tty: true
    network_mode: host