version: "3.3"
services:
  ros-dev:
    image: shiukaheng/stagehands:prod
    entrypoint: ["/scripts/entrypoint.sh"]
    volumes:
      - ./basebot/scripts:/scripts
      - /dev:/dev
      - /dev/bus/usb:/dev/bus/usb
      - /root/name.json
      - /etc/ssh:/etc/ssh
    privileged: true
    stdin_open: true
    tty: true