version: "3.3"
services:
  ros-dev:
    volumes:
      - ./basebot/.vscode:/catkin_ws/.vscode
      - ./basebot/src:/catkin_ws/src
      - ./basebot/map:/map
      - ./basebot/scripts:/scripts
      - ../packages:/catkin_ws/src/stagehands-js/packages
      - ../package.json:/catkin_ws/src/stagehands-js/package.json
      - ../package-lock.json:/catkin_ws/src/stagehands-js/package-lock.json
      - /catkin_ws/devel
      - /catkin_ws/build
      - /catkin_ws/logs
      - /catkin_ws/install
      - ./basebot/sshd_config:/etc/ssh/sshd_config