(cl:defpackage stagehands_ros-srv
  (:use )
  (:export
   "ARUCOAVERAGEPOSE"
   "<ARUCOAVERAGEPOSE-REQUEST>"
   "ARUCOAVERAGEPOSE-REQUEST"
   "<ARUCOAVERAGEPOSE-RESPONSE>"
   "ARUCOAVERAGEPOSE-RESPONSE"
   "ARUCORECORDPOSES"
   "<ARUCORECORDPOSES-REQUEST>"
   "ARUCORECORDPOSES-REQUEST"
   "<ARUCORECORDPOSES-RESPONSE>"
   "ARUCORECORDPOSES-RESPONSE"
   "SETTARGETPOSE"
   "<SETTARGETPOSE-REQUEST>"
   "SETTARGETPOSE-REQUEST"
   "<SETTARGETPOSE-RESPONSE>"
   "SETTARGETPOSE-RESPONSE"
  ))

