// Generated by gencpp from file stagehands_ros/arucoRecordPoses.msg
// DO NOT EDIT!


#ifndef STAGEHANDS_ROS_MESSAGE_ARUCORECORDPOSES_H
#define STAGEHANDS_ROS_MESSAGE_ARUCORECORDPOSES_H

#include <ros/service_traits.h>


#include <stagehands_ros/arucoRecordPosesRequest.h>
#include <stagehands_ros/arucoRecordPosesResponse.h>


namespace stagehands_ros
{

struct arucoRecordPoses
{

typedef arucoRecordPosesRequest Request;
typedef arucoRecordPosesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct arucoRecordPoses
} // namespace stagehands_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stagehands_ros::arucoRecordPoses > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::stagehands_ros::arucoRecordPoses&) { return value(); }
};

template<>
struct DataType< ::stagehands_ros::arucoRecordPoses > {
  static const char* value()
  {
    return "stagehands_ros/arucoRecordPoses";
  }

  static const char* value(const ::stagehands_ros::arucoRecordPoses&) { return value(); }
};


// service_traits::MD5Sum< ::stagehands_ros::arucoRecordPosesRequest> should match
// service_traits::MD5Sum< ::stagehands_ros::arucoRecordPoses >
template<>
struct MD5Sum< ::stagehands_ros::arucoRecordPosesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stagehands_ros::arucoRecordPoses >::value();
  }
  static const char* value(const ::stagehands_ros::arucoRecordPosesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stagehands_ros::arucoRecordPosesRequest> should match
// service_traits::DataType< ::stagehands_ros::arucoRecordPoses >
template<>
struct DataType< ::stagehands_ros::arucoRecordPosesRequest>
{
  static const char* value()
  {
    return DataType< ::stagehands_ros::arucoRecordPoses >::value();
  }
  static const char* value(const ::stagehands_ros::arucoRecordPosesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stagehands_ros::arucoRecordPosesResponse> should match
// service_traits::MD5Sum< ::stagehands_ros::arucoRecordPoses >
template<>
struct MD5Sum< ::stagehands_ros::arucoRecordPosesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stagehands_ros::arucoRecordPoses >::value();
  }
  static const char* value(const ::stagehands_ros::arucoRecordPosesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stagehands_ros::arucoRecordPosesResponse> should match
// service_traits::DataType< ::stagehands_ros::arucoRecordPoses >
template<>
struct DataType< ::stagehands_ros::arucoRecordPosesResponse>
{
  static const char* value()
  {
    return DataType< ::stagehands_ros::arucoRecordPoses >::value();
  }
  static const char* value(const ::stagehands_ros::arucoRecordPosesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STAGEHANDS_ROS_MESSAGE_ARUCORECORDPOSES_H
