// Generated by gencpp from file stagehands_ros/arucoAveragePose.msg
// DO NOT EDIT!


#ifndef STAGEHANDS_ROS_MESSAGE_ARUCOAVERAGEPOSE_H
#define STAGEHANDS_ROS_MESSAGE_ARUCOAVERAGEPOSE_H

#include <ros/service_traits.h>


#include <stagehands_ros/arucoAveragePoseRequest.h>
#include <stagehands_ros/arucoAveragePoseResponse.h>


namespace stagehands_ros
{

struct arucoAveragePose
{

typedef arucoAveragePoseRequest Request;
typedef arucoAveragePoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct arucoAveragePose
} // namespace stagehands_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stagehands_ros::arucoAveragePose > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::stagehands_ros::arucoAveragePose&) { return value(); }
};

template<>
struct DataType< ::stagehands_ros::arucoAveragePose > {
  static const char* value()
  {
    return "stagehands_ros/arucoAveragePose";
  }

  static const char* value(const ::stagehands_ros::arucoAveragePose&) { return value(); }
};


// service_traits::MD5Sum< ::stagehands_ros::arucoAveragePoseRequest> should match
// service_traits::MD5Sum< ::stagehands_ros::arucoAveragePose >
template<>
struct MD5Sum< ::stagehands_ros::arucoAveragePoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stagehands_ros::arucoAveragePose >::value();
  }
  static const char* value(const ::stagehands_ros::arucoAveragePoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stagehands_ros::arucoAveragePoseRequest> should match
// service_traits::DataType< ::stagehands_ros::arucoAveragePose >
template<>
struct DataType< ::stagehands_ros::arucoAveragePoseRequest>
{
  static const char* value()
  {
    return DataType< ::stagehands_ros::arucoAveragePose >::value();
  }
  static const char* value(const ::stagehands_ros::arucoAveragePoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stagehands_ros::arucoAveragePoseResponse> should match
// service_traits::MD5Sum< ::stagehands_ros::arucoAveragePose >
template<>
struct MD5Sum< ::stagehands_ros::arucoAveragePoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stagehands_ros::arucoAveragePose >::value();
  }
  static const char* value(const ::stagehands_ros::arucoAveragePoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stagehands_ros::arucoAveragePoseResponse> should match
// service_traits::DataType< ::stagehands_ros::arucoAveragePose >
template<>
struct DataType< ::stagehands_ros::arucoAveragePoseResponse>
{
  static const char* value()
  {
    return DataType< ::stagehands_ros::arucoAveragePose >::value();
  }
  static const char* value(const ::stagehands_ros::arucoAveragePoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STAGEHANDS_ROS_MESSAGE_ARUCOAVERAGEPOSE_H
