// Generated by gencpp from file stagehands_ros/arucoAveragePoseRequest.msg
// DO NOT EDIT!


#ifndef STAGEHANDS_ROS_MESSAGE_ARUCOAVERAGEPOSEREQUEST_H
#define STAGEHANDS_ROS_MESSAGE_ARUCOAVERAGEPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stagehands_ros
{
template <class ContainerAllocator>
struct arucoAveragePoseRequest_
{
  typedef arucoAveragePoseRequest_<ContainerAllocator> Type;

  arucoAveragePoseRequest_()
    {
    }
  arucoAveragePoseRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct arucoAveragePoseRequest_

typedef ::stagehands_ros::arucoAveragePoseRequest_<std::allocator<void> > arucoAveragePoseRequest;

typedef boost::shared_ptr< ::stagehands_ros::arucoAveragePoseRequest > arucoAveragePoseRequestPtr;
typedef boost::shared_ptr< ::stagehands_ros::arucoAveragePoseRequest const> arucoAveragePoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace stagehands_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stagehands_ros/arucoAveragePoseRequest";
  }

  static const char* value(const ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arucoAveragePoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::stagehands_ros::arucoAveragePoseRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // STAGEHANDS_ROS_MESSAGE_ARUCOAVERAGEPOSEREQUEST_H
