// Generated by gencpp from file stagehands_ros/setTargetPoseRequest.msg
// DO NOT EDIT!


#ifndef STAGEHANDS_ROS_MESSAGE_SETTARGETPOSEREQUEST_H
#define STAGEHANDS_ROS_MESSAGE_SETTARGETPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stagehands_ros
{
template <class ContainerAllocator>
struct setTargetPoseRequest_
{
  typedef setTargetPoseRequest_<ContainerAllocator> Type;

  setTargetPoseRequest_()
    : xPos(0.0)
    , yPos(0.0)
    , rotationQuaternion()
    , micHeight(0.0)
    , ledAnimation()
    , ledRGBColour()
    , flashFrequency(0.0)  {
    }
  setTargetPoseRequest_(const ContainerAllocator& _alloc)
    : xPos(0.0)
    , yPos(0.0)
    , rotationQuaternion(_alloc)
    , micHeight(0.0)
    , ledAnimation(_alloc)
    , ledRGBColour(_alloc)
    , flashFrequency(0.0)  {
  (void)_alloc;
    }



   typedef double _xPos_type;
  _xPos_type xPos;

   typedef double _yPos_type;
  _yPos_type yPos;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _rotationQuaternion_type;
  _rotationQuaternion_type rotationQuaternion;

   typedef double _micHeight_type;
  _micHeight_type micHeight;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ledAnimation_type;
  _ledAnimation_type ledAnimation;

   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _ledRGBColour_type;
  _ledRGBColour_type ledRGBColour;

   typedef double _flashFrequency_type;
  _flashFrequency_type flashFrequency;





  typedef boost::shared_ptr< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setTargetPoseRequest_

typedef ::stagehands_ros::setTargetPoseRequest_<std::allocator<void> > setTargetPoseRequest;

typedef boost::shared_ptr< ::stagehands_ros::setTargetPoseRequest > setTargetPoseRequestPtr;
typedef boost::shared_ptr< ::stagehands_ros::setTargetPoseRequest const> setTargetPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator1> & lhs, const ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.xPos == rhs.xPos &&
    lhs.yPos == rhs.yPos &&
    lhs.rotationQuaternion == rhs.rotationQuaternion &&
    lhs.micHeight == rhs.micHeight &&
    lhs.ledAnimation == rhs.ledAnimation &&
    lhs.ledRGBColour == rhs.ledRGBColour &&
    lhs.flashFrequency == rhs.flashFrequency;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator1> & lhs, const ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stagehands_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aaeb198e8239ff7679a0d51a1562b12c";
  }

  static const char* value(const ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaaeb198e8239ff76ULL;
  static const uint64_t static_value2 = 0x79a0d51a1562b12cULL;
};

template<class ContainerAllocator>
struct DataType< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stagehands_ros/setTargetPoseRequest";
  }

  static const char* value(const ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 xPos\n"
"float64 yPos\n"
"float64[] rotationQuaternion\n"
"float64 micHeight\n"
"string ledAnimation\n"
"int64[] ledRGBColour\n"
"float64 flashFrequency\n"
;
  }

  static const char* value(const ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xPos);
      stream.next(m.yPos);
      stream.next(m.rotationQuaternion);
      stream.next(m.micHeight);
      stream.next(m.ledAnimation);
      stream.next(m.ledRGBColour);
      stream.next(m.flashFrequency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setTargetPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stagehands_ros::setTargetPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "xPos: ";
    Printer<double>::stream(s, indent + "  ", v.xPos);
    s << indent << "yPos: ";
    Printer<double>::stream(s, indent + "  ", v.yPos);
    s << indent << "rotationQuaternion[]" << std::endl;
    for (size_t i = 0; i < v.rotationQuaternion.size(); ++i)
    {
      s << indent << "  rotationQuaternion[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.rotationQuaternion[i]);
    }
    s << indent << "micHeight: ";
    Printer<double>::stream(s, indent + "  ", v.micHeight);
    s << indent << "ledAnimation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ledAnimation);
    s << indent << "ledRGBColour[]" << std::endl;
    for (size_t i = 0; i < v.ledRGBColour.size(); ++i)
    {
      s << indent << "  ledRGBColour[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.ledRGBColour[i]);
    }
    s << indent << "flashFrequency: ";
    Printer<double>::stream(s, indent + "  ", v.flashFrequency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STAGEHANDS_ROS_MESSAGE_SETTARGETPOSEREQUEST_H
