// Generated by gencpp from file stagehands_ros/setTargetPose.msg
// DO NOT EDIT!


#ifndef STAGEHANDS_ROS_MESSAGE_SETTARGETPOSE_H
#define STAGEHANDS_ROS_MESSAGE_SETTARGETPOSE_H

#include <ros/service_traits.h>


#include <stagehands_ros/setTargetPoseRequest.h>
#include <stagehands_ros/setTargetPoseResponse.h>


namespace stagehands_ros
{

struct setTargetPose
{

typedef setTargetPoseRequest Request;
typedef setTargetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setTargetPose
} // namespace stagehands_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stagehands_ros::setTargetPose > {
  static const char* value()
  {
    return "b2641e4b932d1b80a79d7568f7c58323";
  }

  static const char* value(const ::stagehands_ros::setTargetPose&) { return value(); }
};

template<>
struct DataType< ::stagehands_ros::setTargetPose > {
  static const char* value()
  {
    return "stagehands_ros/setTargetPose";
  }

  static const char* value(const ::stagehands_ros::setTargetPose&) { return value(); }
};


// service_traits::MD5Sum< ::stagehands_ros::setTargetPoseRequest> should match
// service_traits::MD5Sum< ::stagehands_ros::setTargetPose >
template<>
struct MD5Sum< ::stagehands_ros::setTargetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stagehands_ros::setTargetPose >::value();
  }
  static const char* value(const ::stagehands_ros::setTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stagehands_ros::setTargetPoseRequest> should match
// service_traits::DataType< ::stagehands_ros::setTargetPose >
template<>
struct DataType< ::stagehands_ros::setTargetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::stagehands_ros::setTargetPose >::value();
  }
  static const char* value(const ::stagehands_ros::setTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stagehands_ros::setTargetPoseResponse> should match
// service_traits::MD5Sum< ::stagehands_ros::setTargetPose >
template<>
struct MD5Sum< ::stagehands_ros::setTargetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stagehands_ros::setTargetPose >::value();
  }
  static const char* value(const ::stagehands_ros::setTargetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stagehands_ros::setTargetPoseResponse> should match
// service_traits::DataType< ::stagehands_ros::setTargetPose >
template<>
struct DataType< ::stagehands_ros::setTargetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::stagehands_ros::setTargetPose >::value();
  }
  static const char* value(const ::stagehands_ros::setTargetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STAGEHANDS_ROS_MESSAGE_SETTARGETPOSE_H
